# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(verbose_name='date published')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True)),
                ('ImgUrl', models.URLField(blank=True)),
                ('ImgName', models.CharField(max_length=20)),
            ],
        ),
    ]
