# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rarity', models.CharField(max_length=10)),
                ('cost', models.PositiveIntegerField(max_length=2)),
                ('arena', models.PositiveIntegerField(max_length=2)),
                ('cardtype', models.CharField(max_length=20)),
                ('ImgUrl', models.URLField(blank=True)),
            ],
        ),
    ]
