# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idName', models.CharField(max_length=20)),
                ('rarity', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('arena', models.IntegerField()),
                ('elixirCost', models.IntegerField()),
            ],
        ),
    ]
