# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0002_cardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='inDeck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
