# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0002_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='arena',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cards',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
