# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0003_auto_20170523_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('R', 'Rare'), ('E', 'Epic'), ('L', 'Legendary')], max_length=20)),
                ('cost', models.PositiveIntegerField()),
                ('arena', models.PositiveIntegerField()),
                ('cardtype', models.CharField(choices=[('T', 'Troop'), ('S', 'Spell'), ('B', 'Building')], max_length=20)),
                ('ImgUrl', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='cards',
        ),
    ]
