# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 15:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0003_auto_20170524_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=8)),
            ],
        ),
    ]
