# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0003_auto_20170524_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('card1', models.CharField(max_length=20)),
                ('card2', models.CharField(max_length=20)),
                ('card3', models.CharField(max_length=20)),
                ('card4', models.CharField(max_length=20)),
                ('card5', models.CharField(max_length=20)),
                ('card6', models.CharField(max_length=20)),
                ('card7', models.CharField(max_length=20)),
                ('card8', models.CharField(max_length=20)),
            ],
        ),
    ]
