# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0004_auto_20170523_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ImgUrl',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
