# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0004_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='board',
        ),
        migrations.AddField(
            model_name='deck',
            name='card1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='deck',
            name='card2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='deck',
            name='card3',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='deck',
            name='card4',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='deck',
            name='card5',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='deck',
            name='card6',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='deck',
            name='card7',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='deck',
            name='card8',
            field=models.IntegerField(default=-1),
        ),
    ]
