# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0005_auto_20170523_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='indeck',
            field=models.BooleanField(default=False),
        ),
    ]
