# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0005_auto_20170527_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cost',
            field=models.FloatField(),
        ),
    ]
