# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0005_searchmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateinfo',
            name='ImgUrl',
            field=models.CharField(max_length=50),
        ),
    ]
