# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0006_auto_20170528_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='card1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card4',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card5',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card6',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card7',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card8',
            field=models.CharField(max_length=20),
        ),
    ]
