# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0006_auto_20170603_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateinfo',
            name='shoutcut',
            field=models.TextField(default='None', max_length=100),
        ),
    ]
